version: '2'
services:
  gtw-mysql:
    #image: mysql:8.0.16
    image: mysql:5.7.20
    # volumes:
    #     - ~/volumes/jhipster/gtw/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=gtw
      - MYSQL_PASSWORD=gtw
      - MYSQL_DATABASE=gtw
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
